default: basicPlots comp2011vs2012

basicPlots: basicPlots.cxx
	g++ -o basicPlots basicPlots.cxx $(shell root-config --cflags --libs)

comp2011vs2012: comp2011vs2012.cxx
	g++ -o comp2011vs2012 comp2011vs2012.cxx $(shell root-config --cflags --libs)

